### ISSUE TITLE
Create binding for Switch component

### ISSUE THREAD

**Issue by bernalrs** [InsidersByte/bs-material-ui#47]
Create a binding for the Switch component as specified in the docs: 

1.  https://material-ui-next.com/api/switch/#switch
2.  Validate that the docs have the same interface as specified in the source code "propTypes"  : https://github.com/mui-org/material-ui/blob/v1-beta/src/Switch/Switch.js

  checked: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
  checkedIcon: PropTypes.node,
  classes: PropTypes.object.isRequired,
  className: PropTypes.string,
  defaultChecked: PropTypes.bool,
  disabled: PropTypes.bool,
  disableRipple: PropTypes.bool,
  icon: PropTypes.node,
  inputProps: PropTypes.object,
  inputRef: PropTypes.func,
  inputType: PropTypes.string,
  name: PropTypes.string,
  onChange: PropTypes.func as   CallBack(oject, boolean)
  tabIndex: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  value: PropTypes.string

Thank

**Comment by Julie-S-Bernal** [comment]
Thank you, I am on it.
